pool:
  vmImage: Hosted Ubuntu 1604
steps:
- task: DockerCompose@0
  displayName: 'Build services'
  inputs:
    azureSubscription: 'VS-Sub-SE'
    azureContainerRegistry: '{"loginServer":"msvib.azurecr.io", "id" : "/subscriptions/93b8da52-87c3-4a1a-8dcb-ab383f4ed6b4/resourceGroups/ms-vib-acr-ase-rg/providers/Microsoft.ContainerRegistry/registries/msvib"}'
    action: 'Build services'

- task: DockerCompose@0
  displayName: 'Push services'
  inputs:
    azureSubscription: 'ACR-SE'
    azureContainerRegistry: '{"loginServer":"msvib.azurecr.io", "id" : "/subscriptions/93b8da52-87c3-4a1a-8dcb-ab383f4ed6b4/resourceGroups/ms-vib-acr-ase-rg/providers/Microsoft.ContainerRegistry/registries/msvib"}'
    action: 'Push services'
    includeLatestTag: true
