version: '3.4'

services:
  web:
    container_name: 'mouna.web.crud'
    build:
      context: .
      dockerfile: Web/Dockerfile
    ports:
     - "8080:80"
    depends_on:
     - mouna.api.crud
     - migration
     - sqldb
  mouna.api.crud:
    container_name: 'mouna.api.crud'
    image: 'mouna.api.crud'
    build:
      context: .
      dockerfile: API/Mouna.Api.Crud/Dockerfile
    ports:
     - "5000:5000"
    depends_on:
     - sqldb
     - migration

  migration:
    container_name: 'flyaway-test'
    build:
      context: .
      dockerfile: Migrations/Dockerfile
    environment:
        SA_USER: "SA"
        SA_PASSWORD: "Welcome@1SA"
    depends_on:
      - sqldb
  sqldb:
    image: "mcr.microsoft.com/mssql/server"
    container_name: 'sqlserver-test'
    environment:
        SA_PASSWORD: "Welcome@1SA"
        ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
